version: '3'

services:
  # PHP-FPM Service
  bitrix:
    container_name: php-fpm
    build:
      context: php-fpm/.
    networks:
      - network_app
    ports:
      - '9000:9000'
    volumes:
      - ./www/:/var/www/bitrix

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    environment:
      - SERVERNAME=${WEB_HOSTNAME}
      - FPM_SERVER=php-fpm
      - FPM_PORT=9000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/bitrix
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - network_app

  # DB Service
  mysql_db:
    image: mysql:8.4
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - network_app
    volumes:
      - ./dbdata:/var/lib/mysql/

  memcached:
    image: memcached:latest
    container_name: memcached
    volumes:
      - ./cache:/var/lib/memcached
    ports:
      - '11211:11211'
    networks:
      - network_app
    environment:
      TZ: Europe/Moscow

networks:
  network_app:
    driver: bridge